// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Church struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Category        string `json:"category"`
	Address         string `json:"address"`
	Pastor          string `json:"pastor"`
	EstablishedDate string `json:"establishedDate"`
}

type Mutation struct {
}

type NewChurch struct {
	Name            string `json:"name"`
	Category        string `json:"category"`
	Address         string `json:"address"`
	Pastor          string `json:"pastor"`
	EstablishedDate string `json:"establishedDate"`
}

type Query struct {
}
