package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/abisalde/go-showcase/client/graph/model"
	"github.com/abisalde/go-showcase/server/proto/church"
)

func (r *mutationResolver) CreateChurch(ctx context.Context, input model.NewChurch) (*model.Church, error) {

	if input.Name == "" || input.Address == "" || input.Pastor == "" {
		return nil, fmt.Errorf("all fields are required")
	}

	newChurch := &model.Church{
		Name:    input.Name,
		Address: input.Address,
		Pastor:  input.Pastor,
	}

	churchClient := church.Church{
		Name:    newChurch.Name,
		Address: newChurch.Address,
		Pastor:  newChurch.Pastor,
	}

	_, err := r.churchClient.CreateChurch(ctx, &churchClient)
	if err != nil {
		return nil, fmt.Errorf("failed to create church: %v", err)
	}

	return newChurch, nil
}

// Churches is the resolver for the churches field.
func (r *queryResolver) Churches(ctx context.Context) ([]*model.Church, error) {

	resp, err := r.churchClient.ListChurches(ctx, &church.ListChurchesRequest{})
	if err != nil {
		return nil, fmt.Errorf("failed to list churches: %v", err)
	}

	var churches []*model.Church
	for _, c := range resp.Churches {
		churches = append(churches, &model.Church{
			ID:      c.Id,
			Name:    c.Name,
			Address: c.Address,
			Pastor:  c.Pastor,
		})
	}

	return churches, nil
}

// GetChurch is the resolver for the getChurch field.
func (r *queryResolver) GetChurch(ctx context.Context, id string) (*model.Church, error) {
	resp, err := r.churchClient.GetChurch(ctx, &church.GetChurchRequest{Id: id})
	if err != nil {
		return nil, fmt.Errorf("failed to get church: %v", err)
	}

	return &model.Church{
		ID:      resp.Church.Id,
		Name:    resp.Church.Name,
		Address: resp.Church.Address,
		Pastor:  resp.Church.Pastor,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
