// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: church/church.proto

package church

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Church struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Pastor          string                 `protobuf:"bytes,4,opt,name=pastor,proto3" json:"pastor,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	EstablishedDate string                 `protobuf:"bytes,6,opt,name=established_date,json=establishedDate,proto3" json:"established_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Church) Reset() {
	*x = Church{}
	mi := &file_church_church_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Church) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Church) ProtoMessage() {}

func (x *Church) ProtoReflect() protoreflect.Message {
	mi := &file_church_church_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Church.ProtoReflect.Descriptor instead.
func (*Church) Descriptor() ([]byte, []int) {
	return file_church_church_proto_rawDescGZIP(), []int{0}
}

func (x *Church) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Church) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Church) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Church) GetPastor() string {
	if x != nil {
		return x.Pastor
	}
	return ""
}

func (x *Church) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Church) GetEstablishedDate() string {
	if x != nil {
		return x.EstablishedDate
	}
	return ""
}

type GetChurchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChurchRequest) Reset() {
	*x = GetChurchRequest{}
	mi := &file_church_church_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChurchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChurchRequest) ProtoMessage() {}

func (x *GetChurchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_church_church_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChurchRequest.ProtoReflect.Descriptor instead.
func (*GetChurchRequest) Descriptor() ([]byte, []int) {
	return file_church_church_proto_rawDescGZIP(), []int{1}
}

func (x *GetChurchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetChurchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Church        *Church                `protobuf:"bytes,1,opt,name=church,proto3" json:"church,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChurchResponse) Reset() {
	*x = GetChurchResponse{}
	mi := &file_church_church_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChurchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChurchResponse) ProtoMessage() {}

func (x *GetChurchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_church_church_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChurchResponse.ProtoReflect.Descriptor instead.
func (*GetChurchResponse) Descriptor() ([]byte, []int) {
	return file_church_church_proto_rawDescGZIP(), []int{2}
}

func (x *GetChurchResponse) GetChurch() *Church {
	if x != nil {
		return x.Church
	}
	return nil
}

type ListChurchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChurchesRequest) Reset() {
	*x = ListChurchesRequest{}
	mi := &file_church_church_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChurchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChurchesRequest) ProtoMessage() {}

func (x *ListChurchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_church_church_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChurchesRequest.ProtoReflect.Descriptor instead.
func (*ListChurchesRequest) Descriptor() ([]byte, []int) {
	return file_church_church_proto_rawDescGZIP(), []int{3}
}

func (x *ListChurchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChurchesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListChurchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Churches      []*Church              `protobuf:"bytes,1,rep,name=churches,proto3" json:"churches,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChurchesResponse) Reset() {
	*x = ListChurchesResponse{}
	mi := &file_church_church_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChurchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChurchesResponse) ProtoMessage() {}

func (x *ListChurchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_church_church_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChurchesResponse.ProtoReflect.Descriptor instead.
func (*ListChurchesResponse) Descriptor() ([]byte, []int) {
	return file_church_church_proto_rawDescGZIP(), []int{4}
}

func (x *ListChurchesResponse) GetChurches() []*Church {
	if x != nil {
		return x.Churches
	}
	return nil
}

func (x *ListChurchesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_church_church_proto protoreflect.FileDescriptor

const file_church_church_proto_rawDesc = "" +
	"\n" +
	"\x13church/church.proto\x12\x06church\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x06Church\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06pastor\x18\x04 \x01(\tR\x06pastor\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12)\n" +
	"\x10established_date\x18\x06 \x01(\tR\x0festablishedDate\"\"\n" +
	"\x10GetChurchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetChurchResponse\x12&\n" +
	"\x06church\x18\x01 \x01(\v2\x0e.church.ChurchR\x06church\"Q\n" +
	"\x13ListChurchesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"j\n" +
	"\x14ListChurchesResponse\x12*\n" +
	"\bchurches\x18\x01 \x03(\v2\x0e.church.ChurchR\bchurches\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xbe\x02\n" +
	"\rChurchService\x12@\n" +
	"\tGetChurch\x12\x18.church.GetChurchRequest\x1a\x19.church.GetChurchResponse\x12I\n" +
	"\fListChurches\x12\x1b.church.ListChurchesRequest\x1a\x1c.church.ListChurchesResponse\x12.\n" +
	"\fCreateChurch\x12\x0e.church.Church\x1a\x0e.church.Church\x12.\n" +
	"\fUpdateChurch\x12\x0e.church.Church\x1a\x0e.church.Church\x12@\n" +
	"\fDeleteChurch\x12\x18.church.GetChurchRequest\x1a\x16.google.protobuf.EmptyB5Z3github.com/abisalde/go-showcase/server/proto/churchb\x06proto3"

var (
	file_church_church_proto_rawDescOnce sync.Once
	file_church_church_proto_rawDescData []byte
)

func file_church_church_proto_rawDescGZIP() []byte {
	file_church_church_proto_rawDescOnce.Do(func() {
		file_church_church_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_church_church_proto_rawDesc), len(file_church_church_proto_rawDesc)))
	})
	return file_church_church_proto_rawDescData
}

var file_church_church_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_church_church_proto_goTypes = []any{
	(*Church)(nil),               // 0: church.Church
	(*GetChurchRequest)(nil),     // 1: church.GetChurchRequest
	(*GetChurchResponse)(nil),    // 2: church.GetChurchResponse
	(*ListChurchesRequest)(nil),  // 3: church.ListChurchesRequest
	(*ListChurchesResponse)(nil), // 4: church.ListChurchesResponse
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_church_church_proto_depIdxs = []int32{
	0, // 0: church.GetChurchResponse.church:type_name -> church.Church
	0, // 1: church.ListChurchesResponse.churches:type_name -> church.Church
	1, // 2: church.ChurchService.GetChurch:input_type -> church.GetChurchRequest
	3, // 3: church.ChurchService.ListChurches:input_type -> church.ListChurchesRequest
	0, // 4: church.ChurchService.CreateChurch:input_type -> church.Church
	0, // 5: church.ChurchService.UpdateChurch:input_type -> church.Church
	1, // 6: church.ChurchService.DeleteChurch:input_type -> church.GetChurchRequest
	2, // 7: church.ChurchService.GetChurch:output_type -> church.GetChurchResponse
	4, // 8: church.ChurchService.ListChurches:output_type -> church.ListChurchesResponse
	0, // 9: church.ChurchService.CreateChurch:output_type -> church.Church
	0, // 10: church.ChurchService.UpdateChurch:output_type -> church.Church
	5, // 11: church.ChurchService.DeleteChurch:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_church_church_proto_init() }
func file_church_church_proto_init() {
	if File_church_church_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_church_church_proto_rawDesc), len(file_church_church_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_church_church_proto_goTypes,
		DependencyIndexes: file_church_church_proto_depIdxs,
		MessageInfos:      file_church_church_proto_msgTypes,
	}.Build()
	File_church_church_proto = out.File
	file_church_church_proto_goTypes = nil
	file_church_church_proto_depIdxs = nil
}
