// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: church/church.proto

package church

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChurchService_GetChurch_FullMethodName    = "/church.ChurchService/GetChurch"
	ChurchService_ListChurches_FullMethodName = "/church.ChurchService/ListChurches"
	ChurchService_CreateChurch_FullMethodName = "/church.ChurchService/CreateChurch"
	ChurchService_UpdateChurch_FullMethodName = "/church.ChurchService/UpdateChurch"
	ChurchService_DeleteChurch_FullMethodName = "/church.ChurchService/DeleteChurch"
)

// ChurchServiceClient is the client API for ChurchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChurchServiceClient interface {
	GetChurch(ctx context.Context, in *GetChurchRequest, opts ...grpc.CallOption) (*GetChurchResponse, error)
	ListChurches(ctx context.Context, in *ListChurchesRequest, opts ...grpc.CallOption) (*ListChurchesResponse, error)
	CreateChurch(ctx context.Context, in *Church, opts ...grpc.CallOption) (*Church, error)
	UpdateChurch(ctx context.Context, in *Church, opts ...grpc.CallOption) (*Church, error)
	DeleteChurch(ctx context.Context, in *GetChurchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type churchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChurchServiceClient(cc grpc.ClientConnInterface) ChurchServiceClient {
	return &churchServiceClient{cc}
}

func (c *churchServiceClient) GetChurch(ctx context.Context, in *GetChurchRequest, opts ...grpc.CallOption) (*GetChurchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChurchResponse)
	err := c.cc.Invoke(ctx, ChurchService_GetChurch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *churchServiceClient) ListChurches(ctx context.Context, in *ListChurchesRequest, opts ...grpc.CallOption) (*ListChurchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChurchesResponse)
	err := c.cc.Invoke(ctx, ChurchService_ListChurches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *churchServiceClient) CreateChurch(ctx context.Context, in *Church, opts ...grpc.CallOption) (*Church, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Church)
	err := c.cc.Invoke(ctx, ChurchService_CreateChurch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *churchServiceClient) UpdateChurch(ctx context.Context, in *Church, opts ...grpc.CallOption) (*Church, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Church)
	err := c.cc.Invoke(ctx, ChurchService_UpdateChurch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *churchServiceClient) DeleteChurch(ctx context.Context, in *GetChurchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChurchService_DeleteChurch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChurchServiceServer is the server API for ChurchService service.
// All implementations must embed UnimplementedChurchServiceServer
// for forward compatibility.
type ChurchServiceServer interface {
	GetChurch(context.Context, *GetChurchRequest) (*GetChurchResponse, error)
	ListChurches(context.Context, *ListChurchesRequest) (*ListChurchesResponse, error)
	CreateChurch(context.Context, *Church) (*Church, error)
	UpdateChurch(context.Context, *Church) (*Church, error)
	DeleteChurch(context.Context, *GetChurchRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedChurchServiceServer()
}

// UnimplementedChurchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChurchServiceServer struct{}

func (UnimplementedChurchServiceServer) GetChurch(context.Context, *GetChurchRequest) (*GetChurchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChurch not implemented")
}
func (UnimplementedChurchServiceServer) ListChurches(context.Context, *ListChurchesRequest) (*ListChurchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChurches not implemented")
}
func (UnimplementedChurchServiceServer) CreateChurch(context.Context, *Church) (*Church, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChurch not implemented")
}
func (UnimplementedChurchServiceServer) UpdateChurch(context.Context, *Church) (*Church, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChurch not implemented")
}
func (UnimplementedChurchServiceServer) DeleteChurch(context.Context, *GetChurchRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChurch not implemented")
}
func (UnimplementedChurchServiceServer) mustEmbedUnimplementedChurchServiceServer() {}
func (UnimplementedChurchServiceServer) testEmbeddedByValue()                       {}

// UnsafeChurchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChurchServiceServer will
// result in compilation errors.
type UnsafeChurchServiceServer interface {
	mustEmbedUnimplementedChurchServiceServer()
}

func RegisterChurchServiceServer(s grpc.ServiceRegistrar, srv ChurchServiceServer) {
	// If the following call panics, it indicates UnimplementedChurchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChurchService_ServiceDesc, srv)
}

func _ChurchService_GetChurch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChurchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurchServiceServer).GetChurch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurchService_GetChurch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurchServiceServer).GetChurch(ctx, req.(*GetChurchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChurchService_ListChurches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChurchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurchServiceServer).ListChurches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurchService_ListChurches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurchServiceServer).ListChurches(ctx, req.(*ListChurchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChurchService_CreateChurch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Church)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurchServiceServer).CreateChurch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurchService_CreateChurch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurchServiceServer).CreateChurch(ctx, req.(*Church))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChurchService_UpdateChurch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Church)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurchServiceServer).UpdateChurch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurchService_UpdateChurch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurchServiceServer).UpdateChurch(ctx, req.(*Church))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChurchService_DeleteChurch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChurchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurchServiceServer).DeleteChurch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurchService_DeleteChurch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurchServiceServer).DeleteChurch(ctx, req.(*GetChurchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChurchService_ServiceDesc is the grpc.ServiceDesc for ChurchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChurchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "church.ChurchService",
	HandlerType: (*ChurchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChurch",
			Handler:    _ChurchService_GetChurch_Handler,
		},
		{
			MethodName: "ListChurches",
			Handler:    _ChurchService_ListChurches_Handler,
		},
		{
			MethodName: "CreateChurch",
			Handler:    _ChurchService_CreateChurch_Handler,
		},
		{
			MethodName: "UpdateChurch",
			Handler:    _ChurchService_UpdateChurch_Handler,
		},
		{
			MethodName: "DeleteChurch",
			Handler:    _ChurchService_DeleteChurch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "church/church.proto",
}
